import { MenuGroupItem } from './menuGroupItem'

export const MENU: MenuGroupItem[] = [
    { groupName: "Morning Special", list: [
        { url: "../assets/foody/alooparatha1.jpg", name: "Aalu Paratha", cost: "60" },
        { url: "", name: "Aalu Pyaz Paratha", cost: "60" },
        { url: "", name: "Gobhi Paratha", cost: "70" },
        { url: "", name: "Paneer Paratha", cost: "80" },
        { url: "", name: "FoodJunction Special Paratha", cost: "90" }
    ] },
    { groupName: "Starter", list: [
        { url: "../assets/foody/tomatosoup1.jpg", name: "Tomato Soup", cost: "70" },
        { url: "", name: "Vegetable Soup", cost: "70" },
        { url: "", name: "Sweet Corn Soup", cost: "70" },
        { url: "", name: "Mashroom Soup", cost: "80" },
        { url: "", name: "Tomato Garlic & Ginger Soup", cost: "80" },
        { url: "", name: "Hot N Sour Soup", cost: "80" },
        { url: "", name: "Manchow Soup", cost: "80" },
    ] },
    { groupName: "Chinese", list: [
        { url: "", name: "Veg Maggi", cost: "60" },
        { url: "", name: "Veg Momos/Fried", cost: "50/60" },
        { url: "", name: "Veg Paneer Momos/Fried", cost: "70/80" },
        { url: "", name: "Veg Tandoori Momos/Fried", cost: "120" },
        { url: "", name: "French Fries", cost: "80" },
        { url: "", name: "Fried Rice", cost: "100" },
        { url: "", name: "Chowmein", cost: "100"},
        { url: "", name: "Hakka Noddles", cost: "100"},
        { url: "", name: "Singapuri Noddles", cost: "100"},
        { url: "", name: "Chilli Garlic Noddles", cost: "100"},
        { url: "", name: "Paneer Noodles", cost: "120"},
        { url: "", name: "Chilly Potato", cost: "70/130"},
        { url: "", name: " Honey Chilly Potato", cost: "80/140"},
        { url: "", name: "Veg Manchurian(dry&gravy)", cost: "120"},
        { url: "", name: "Paneer Manchurian(dry&gravy)", cost: "150"},
        { url: "", name: "Chilli Chaap", cost: "80/150"},
        { url: "", name: "Chilli Paneer(dry&gravy", cost: "80/150"},
        { url: "", name: "Chilli Mashroom", cost: "80/150"},
        { url: "", name: "Mashroom Salt And Pepper", cost: "160"},
        { url: "", name: "F.J Special", cost: "180"}       
    ] },
    { groupName: "Tandoor Se", list: [
        { url: "", name: "Soya Chaap/Paneer Tikka", cost: "80/140" },
        { url: "", name: "Lemon Tikka", cost: "80/140" },
        { url: "", name: "Malai Chaap/Paneer Tikka", cost: "90/160" },
        { url: "", name: "Achari Chaap Tikka", cost: "90/160" },
        { url: "", name: "Kali Mirch Chaap Tikka", cost: "90/160" },
        { url: "", name: "Butter Chaap", cost: "90/160" },
        { url: "", name: "Chatpati Chaap", cost: "90/160" },
        { url: "", name: "Mashroom Tikka", cost: "160" },
        { url: "", name: "Mix Tikka", cost: "160" },
    ] },
    { groupName: "Ghar Ka Swaad", list: [
        { url: "", name: "Dal Fry", cost: "60/100" },
        { url: "", name: "Dal Tadka", cost: "60/100" },
        { url: "", name: "Rajma", cost: "60/100" },
        { url: "", name: "Chana Masala", cost: "60/100" },
        { url: "", name: "Dal Makhni", cost: "70/120" },
        { url: "", name: "Dal Punjabi", cost: "100" },
        { url: "", name: "Dal Dhaba", cost: "100" },
    ] },
    { groupName: "Kadahi Se", list: [
        { url: "", name: "Matar Paneer", cost: "70/130" },
        { url: "", name: "Palak Paneer", cost: "70/130" },
        { url: "", name: "Kadahi Paneer", cost: "80/140" },
        { url: "", name: "Shahi Paneer", cost: "80/140" },
        { url: "", name: "Paneer Do Pyaaza", cost: "80/140" },
        { url: "", name: "Paneer Bhurji", cost: "80/140" },
        { url: "", name: "Paneer Korma", cost: "80/140" },
        { url: "", name: "Paneer Butter Masala", cost: "80/140" },
        { url: "", name: "Handi Paneer", cost: "80/140" },
        { url: "", name: "Malai Kofta", cost: "80/140" },
        { url: "", name: "Matar Mashroom", cost: "80/140" },
        { url: "", name: "Paneer Lababdar", cost: "90/150" },
        { url: "", name: "Kadahi Mashroom", cost: "90/150" },
        { url: "", name: "Paneer Mashroom", cost: "90/150" },
        { url: "", name: "Matar Methi Malai", cost: "160" },
        { url: "", name: "Navratn Korma", cost: "80" },
    ] },
    { groupName: "Seasonable (Veg)", list: [
        { url: "", name: "Aalu jeera", cost: "60/100" },
        { url: "", name: "Gobhi Masala", cost: "60/100" },
        { url: "", name: "Aalu Gobhi", cost: "60/100" },
        { url: "", name: "Dum Aalu", cost: "60/100" },
        { url: "", name: "Seasonal Vegetable", cost: "60/100" },
        { url: "", name: "Mix Veg", cost: "60/100" },
     
    ] },
    { groupName: "Richy Rice", list: [
        { url: "", name: "Plain Rice", cost: "70" },
        { url: "", name: "Rajma + Chawal", cost: "70" },
        { url: "", name: "Chole + Chawal", cost: "70" },
        { url: "", name: "Daal + Chawal", cost: "70" },
        { url: "", name: "Jeera Rice", cost: "80" },
        { url: "", name: "Matar Pulav", cost: "100" },
        { url: "", name: "Veg Pulav", cost: "120" },
        { url: "", name: "Veg Biryani", cost: "130" },
     
    ] },
    { groupName: "Raita & Salad", list: [
        { url: "", name: "Boondi Raita", cost: "60" },
        { url: "", name: "Veg Raita", cost: "70" },
        { url: "", name: "Pineabble Raita", cost: "80" },
        { url: "", name: "Green Salad", cost: "80" },
        { url: "", name: "Onion Salad", cost: "50" },
        { url: "", name: "Roasted Papad(2pc)", cost: "20" },
        { url: "", name: "Masala Papad", cost: "30" },
     
    ] },
    { groupName: "Chaap Gravy", list: [
        { url: "", name: "Tawa Chaap Gravy", cost: "80/150" },
        { url: "", name: "Soya Chaap Gravy", cost: "80/150" },
        { url: "", name: "Tawa Paneer Gravy", cost: "90/160" },
        { url: "", name: "Keema Chaap Gravy", cost: "90/160" },
        { url: "", name: "Tawa Mashroom Gravy", cost: "180" },     
    ] },
    { groupName: "Chulhe Se", list: [
        { url: "", name: "Rumali Roti", cost: "10" },
        { url: "", name: "Tandoori Roti", cost: "10" },
        { url: "", name: "Plain Naan", cost: "25" },
        { url: "", name: "Butter Naan", cost: "30" },
        { url: "", name: "Lachchha Paratha", cost: "30" },
        { url: "", name: "Missi Roti", cost: "30" }, 
        { url: "", name: "Stuff Naan", cost: "40" },
        { url: "", name: "Paneer Stuff Naan", cost: "40" },  
    ] },
    { groupName: "Beverages", list: [
        { url: "", name: "Mineral Water", cost: "On Mrp" },
        { url: "", name: "Cold Drink", cost: "On Mrp" },
        { url: "", name: "Mix Fruit Juice", cost: "40/60" },
        { url: "", name: "Mausmi Juice", cost: "40/60" },
        { url: "", name: "Pineapple Juice", cost: "40/160" },
        { url: "", name: "Anaar Juice", cost: "40/60" }, 
        { url: "", name: "Banana Shake", cost: "40/60" },
        { url: "", name: "Papaya Shake", cost: "40/60" },
        { url: "", name: "Cold Coffee With Ice Cream", cost: "40/60" },  
    ] },
    { groupName: "Thali", list: [
        { url: "", name: "Regular Thali(Daal Fry, Matar Paneer, 2 Tandoori Roti, Rice, Salad Pickle)", cost: "100" },
        { url: "", name: "Special Thali(Rajma, Sahi Panner, 2 Tandoori Roti, Rice, Salad, Raita, Pickle)", cost: "140" },
        { url: "", name: "FoodJuntion Thali(Dal Makhni,Panner Butter Masala, 1 Butter Naan, 1 Laccha Paratha or 3"+
        " Tandoori Roti, Rice, Salad, Raita, Pickle, Chatni)", cost: "170" },
    ] },
];